scan_filter_chain:
  # (Opcional) Recorte angular: deja solo el sector que usarás
  - name: angular_crop
    type: LaserScanAngularBoundsFilter
    params:
      lower_angle: -1.57     # -90 rad  (ajústalo a tu FOV útil)
      upper_angle:  1.57     #  +90 rad

  # Recorte por distancia: quita suelo demasiado cerca y ecos lejanos
  - name: range_clip
    type: LaserScanRangeFilter
    params:
      lower_threshold: 0.07   # m  (sube si ves suelo)
      upper_threshold: 6.0    # m  (ajusta a tu sensor)

  # Suavizado robusto: mediana (quita picos aislados)
  - name: median
    type: LaserScanMedianFilter
    params:
      window: 5               # 3 o 5 funciona bien

  # Anti-speckle: elimina ecos sueltos entre vecinos angulares
  - name: speckle
    type: LaserScanSpeckleFilter
    params:
      max_range: 0.08         # m de tolerancia entre vecinos (0.05–0.12 típico)
      filter_type: 0          # usa 0/1 según comportamiento que prefieras
